-- Migración para refactorizar estructura de coils
-- Cambiar de coils separados subir/bajar a un único coil de estado

-- Renombrar columnas existentes para preservar datos
ALTER TABLE PILONAS RENAME COLUMN COIL_SUBIR TO COIL_ESTADO_OLD;
ALTER TABLE PILONAS RENAME COLUMN COIL_BAJAR TO COIL_BAJADA_PUNTUAL;

-- Crear nuevas columnas con la estructura deseada
ALTER TABLE PILONAS ADD COLUMN COIL_ESTADO_SUBIDA_BAJADA INTEGER;
ALTER TABLE PILONAS ADD COLUMN COIL_FORZADA_ABAJO INTEGER;
ALTER TABLE PILONAS ADD COLUMN COIL_FORZADA_ARRIBA INTEGER;

-- Agregar columnas para puertos específicos de las nuevas coils
ALTER TABLE PILONAS ADD COLUMN PUERTO_COIL_ESTADO_SUBIDA_BAJADA INTEGER;
ALTER TABLE PILONAS ADD COLUMN PUERTO_COIL_FORZADA_ABAJO INTEGER;
ALTER TABLE PILONAS ADD COLUMN PUERTO_COIL_FORZADA_ARRIBA INTEGER;

-- Agregar columnas para unit IDs específicos
ALTER TABLE PILONAS ADD COLUMN UNIT_ID_COIL_ESTADO_SUBIDA_BAJADA INTEGER;
ALTER TABLE PILONAS ADD COLUMN UNIT_ID_COIL_FORZADA_ABAJO INTEGER;
ALTER TABLE PILONAS ADD COLUMN UNIT_ID_COIL_FORZADA_ARRIBA INTEGER;

-- Agregar tipos de registros para las nuevas coils
ALTER TABLE PILONAS ADD COLUMN TIPO_COIL_ESTADO_SUBIDA_BAJADA TEXT DEFAULT 'COIL';
ALTER TABLE PILONAS ADD COLUMN TIPO_COIL_BAJADA_PUNTUAL TEXT DEFAULT 'COIL';
ALTER TABLE PILONAS ADD COLUMN TIPO_COIL_FORZADA_ABAJO TEXT DEFAULT 'COIL';
ALTER TABLE PILONAS ADD COLUMN TIPO_COIL_FORZADA_ARRIBA TEXT DEFAULT 'COIL';

-- Agregar modos de operación
ALTER TABLE PILONAS ADD COLUMN MODO_COIL_ESTADO_SUBIDA_BAJADA TEXT DEFAULT 'RW';
ALTER TABLE PILONAS ADD COLUMN MODO_COIL_BAJADA_PUNTUAL TEXT DEFAULT 'W';
ALTER TABLE PILONAS ADD COLUMN MODO_COIL_FORZADA_ABAJO TEXT DEFAULT 'RW';
ALTER TABLE PILONAS ADD COLUMN MODO_COIL_FORZADA_ARRIBA TEXT DEFAULT 'RW';

-- Migrar datos existentes (usar el coil de estado anterior como base)
UPDATE PILONAS SET 
    COIL_ESTADO_SUBIDA_BAJADA = COIL_ESTADO_OLD,
    PUERTO_COIL_ESTADO_SUBIDA_BAJADA = PUERTO_COIL_ESTADO,
    UNIT_ID_COIL_ESTADO_SUBIDA_BAJADA = UNIT_ID_COIL_ESTADO
WHERE COIL_ESTADO_OLD IS NOT NULL;

-- Limpiar columnas obsoletas (comentadas por seguridad, ejecutar manualmente después de verificar)
-- ALTER TABLE PILONAS DROP COLUMN COIL_ESTADO_OLD;
-- ALTER TABLE PILONAS DROP COLUMN COIL_ESTADO;
-- ALTER TABLE PILONAS DROP COLUMN PUERTO_COIL_SUBIR;
-- ALTER TABLE PILONAS DROP COLUMN PUERTO_COIL_BAJAR;
-- ALTER TABLE PILONAS DROP COLUMN UNIT_ID_COIL_SUBIR;
-- ALTER TABLE PILONAS DROP COLUMN UNIT_ID_COIL_BAJAR;
-- ALTER TABLE PILONAS DROP COLUMN TIPO_COIL_SUBIR;
-- ALTER TABLE PILONAS DROP COLUMN TIPO_COIL_BAJAR;
-- ALTER TABLE PILONAS DROP COLUMN MODO_COIL_SUBIR;
-- ALTER TABLE PILONAS DROP COLUMN MODO_COIL_BAJAR;
